use_frameworks!

platform :ios, '9.0'

target 'EffUIUtils_Example' do
  pod 'EffUIUtils', :path => '../'

  target 'EffUIUtils_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
